version: '3'
services: 
    redis:
        image: redis
        container_name: redis-6379
        ports: 
            - "6379:6379"

    mysql:
        image: mysql
        container_name: mysql-3306
        volumes: 
            - /data/mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: sky_main
            MYSQL_ROOT_PASSWORD: 12345678 
        ports: 
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    celery-worker:
        build: .
        container_name: celery-worker
        command: celery -A celery_worker.app worker --loglevel=info -E
        links: 
            - "mysql:mysql"

    celery-beat:
        build: .
        container_name: celery-beat
        command: celery beat -A celery_worker
